Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 99, in <module>
    args.test_envs, hparams)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/datasets.py", line 161, in __init__
    self.rotate_dataset, (1, 28, 28,), 10)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/datasets.py", line 91, in __init__
    original_dataset_tr = MNIST(root, train=True, download=True)
  File "/home/jcaudet/.local/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 79, in __init__
    self.download()
  File "/home/jcaudet/.local/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 140, in download
    os.makedirs(self.raw_folder, exist_ok=True)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 1 more time]
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/my'
0it [00:00, ?it/s]Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 99, in <module>
    args.test_envs, hparams)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/datasets.py", line 161, in __init__
    self.rotate_dataset, (1, 28, 28,), 10)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/datasets.py", line 91, in __init__
    original_dataset_tr = MNIST(root, train=True, download=True)
  File "/home/jcaudet/.local/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 79, in __init__
    self.download()
  File "/home/jcaudet/.local/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 146, in download
    download_and_extract_archive(url, download_root=self.raw_folder, filename=filename, md5=md5)
  File "/home/jcaudet/.local/lib/python3.6/site-packages/torchvision/datasets/utils.py", line 256, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/home/jcaudet/.local/lib/python3.6/site-packages/torchvision/datasets/utils.py", line 84, in download_url
    raise e
  File "/home/jcaudet/.local/lib/python3.6/site-packages/torchvision/datasets/utils.py", line 72, in download_url
    reporthook=gen_bar_updater()
  File "/usr/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
0it [00:00, ?it/s]
0it [00:00, ?it/s]Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 99, in <module>
    args.test_envs, hparams)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/datasets.py", line 161, in __init__
    self.rotate_dataset, (1, 28, 28,), 10)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/datasets.py", line 91, in __init__
    original_dataset_tr = MNIST(root, train=True, download=True)
  File "/home/jcaudet/.local/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 79, in __init__
    self.download()
  File "/home/jcaudet/.local/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 146, in download
    download_and_extract_archive(url, download_root=self.raw_folder, filename=filename, md5=md5)
  File "/home/jcaudet/.local/lib/python3.6/site-packages/torchvision/datasets/utils.py", line 256, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/home/jcaudet/.local/lib/python3.6/site-packages/torchvision/datasets/utils.py", line 84, in download_url
    raise e
  File "/home/jcaudet/.local/lib/python3.6/site-packages/torchvision/datasets/utils.py", line 72, in download_url
    reporthook=gen_bar_updater()
  File "/usr/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 99, in <module>
    args.test_envs, hparams)
  File "/home/jcaudet/.local/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 83, in __init__
    ' You can use download=True to download it')
RuntimeError: Dataset not found. You can use download=True to download it
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 99, in <module>
    args.test_envs, hparams)
  File "/home/jcaudet/.local/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 83, in __init__
    ' You can use download=True to download it')
RuntimeError: Dataset not found. You can use download=True to download it
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 99, in <module>
    args.test_envs, hparams)
  File "/home/jcaudet/.local/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 83, in __init__
    ' You can use download=True to download it')
RuntimeError: Dataset not found. You can use download=True to download it
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 99, in <module>
    args.test_envs, hparams)
  File "/home/jcaudet/.local/lib/python3.6/site-packages/torchvision/datasets/mnist.py", line 83, in __init__
    ' You can use download=True to download it')
RuntimeError: Dataset not found. You can use download=True to download it
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 98, in <module>
    dataset = vars(datasets)[args.dataset](args.data_dir,
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torchvision/datasets/mnist.py", line 82, in __init__
    raise RuntimeError('Dataset not found.' +
RuntimeError: Dataset not found. You can use download=True to download it
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 118, in <module>
    for env_i, env in enumerate(dataset):
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torchvision/datasets/mnist.py", line 106, in __getitem__
    img = self.transform(img)
TypeError: 'dict' object is not callable
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 94, in update
    return {'loss': loss.item()}
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 172, in <module>
    algorithm = algorithm_class(dataset.input_shape, dataset.num_classes,
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 877, in __init__
    self.tau = hparams["agreement_thresh"]
KeyError: 'agreement_thresh'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 891, in update
    grads = self.get_masked_grad(self.tau,
TypeError: get_masked_grad() got an unexpected keyword argument 'params'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 178, in <module>
    algorithm.to(device)
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 612, in to
    return self._apply(convert)
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 610, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 893, in update
    grads = self.get_masked_grad(self.tau,
TypeError: get_masked_grad() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 893, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
TypeError: get_masked_grad() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 893, in update
    
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 902, in get_masked_grad
    
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 202, in grad
    return Variable._execution_engine.run_backward(
RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling backward the first time.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 891, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 901, in get_masked_grad
    gradients[-1][0] = gradients[-1][0] / gradients[-1][0].norm()
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 891, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 902, in get_masked_grad
    gradients[-1][0] = gradients[-1][0] / gradients[-1][0].norm()
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 891, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 902, in get_masked_grad
    print(gradients.shape)
AttributeError: 'list' object has no attribute 'shape'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 891, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 903, in get_masked_grad
    gradients[-1][0] = gradients[-1][0] / gradients[-1][0].norm()
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 891, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 902, in get_masked_grad
    print(gradients[0].shape)
AttributeError: 'list' object has no attribute 'shape'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 891, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 903, in get_masked_grad
    gradients[-1][0] = gradients[-1][0] / gradients[-1][0].norm()
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 891, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 905, in get_masked_grad
    gradients[-1][0] = gradients[-1][0] / gradients[-1][0].norm()
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 891, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 905, in get_masked_grad
    print(gradients[-1][0].shape)
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 891, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 904, in get_masked_grad
    print(len(gradients[1][0]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 891, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 905, in get_masked_grad
    print(gradients[-1][0].shape)
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 891, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 905, in get_masked_grad
    print(gradients[1][0].shape)
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 891, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 904, in get_masked_grad
    print(len(g[0]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 891, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 905, in get_masked_grad
    print(len(g[0]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 891, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 905, in get_masked_grad
    print(len(g[0]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 891, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 906, in get_masked_grad
    print(len(g[0]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 891, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 906, in get_masked_grad
    print(len(g[0]))
IndexError: tuple index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 891, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 900, in get_masked_grad
    g = torch.autograd.grad(loss, parameters)
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 202, in grad
    return Variable._execution_engine.run_backward(
RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling backward the first time.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 891, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 901, in get_masked_grad
    g = torch.autograd.grad(loss, parameters, retain_graph=True)
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 202, in grad
    return Variable._execution_engine.run_backward(
RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling backward the first time.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 891, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 907, in get_masked_grad
    print(len(g[0]))
IndexError: tuple index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 891, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 909, in get_masked_grad
    gradients[-1][0] = gradients[-1][0] / gradients[-1][0].norm()
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 891, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 908, in get_masked_grad
    print(len(gradients[-1][0]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 891, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 908, in get_masked_grad
    print(len(gradients[-1][0]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 889, in update
    grad = list(autograd.grad(loss, self.network.parameters(), create_graph=True))
NameError: name 'parameters' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 893, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 931, in get_masked_grad
    return g_masked
UnboundLocalError: local variable 'g_masked' referenced before assignment
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 893, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 931, in get_masked_grad
    return g_masked
UnboundLocalError: local variable 'g_masked' referenced before assignment
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 889, in update
    gradiends.append( list(autograd.grad(loss, self.network.parameters(), retain_graph=True)) )
NameError: name 'gradiends' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 892, in update
    grads = self.get_masked_grad(self.tau, losses, self.network.parameters())
NameError: name 'losses' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 893, in update
    grads = self.mask_grads(self.tau, gradients)
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'ILC' object has no attribute 'mask_grads'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 893, in update
    grads = self.mask_grads(self.tau, gradients)
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'ILC' object has no attribute 'mask_grads'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 895, in update
    grads = self.mask_grads(self.tau, gradients)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 902, in mask_grads
    for ge_all, parameter in zip(zip(*gradients), parameters):
NameError: name 'parameters' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 895, in update
    grads = self.mask_grads(self.tau, gradients)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 904, in mask_grads
    ge_cat = torch.cat(ge_all)
TypeError: expected Tensor as element 0 in argument 0, but got tuple
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 895, in update
    grads = self.mask_grads(self.tau, gradients)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 912, in mask_grads
    > len(losses) * tau).int()
NameError: name 'losses' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 901, in update
    return {'loss': losses.sum()}
NameError: name 'losses' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 903, in update
    
NameError: name 'losses' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 226, in <module>
    results[key] = np.mean(val)
  File "<__array_function__ internals>", line 5, in mean
  File "/home/jcaudet/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 3419, in mean
    return _methods._mean(a, axis=axis, dtype=dtype,
  File "/home/jcaudet/.local/lib/python3.8/site-packages/numpy/core/_methods.py", line 162, in _mean
    arr = asanyarray(a)
  File "/home/jcaudet/.local/lib/python3.8/site-packages/numpy/core/_asarray.py", line 171, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/tensor.py", line 630, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 230, in <module>
    acc = misc.accuracy(algorithm, loader, weights, device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/lib/misc.py", line 115, in accuracy
    for x, y in loader:
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/lib/fast_data_loader.py", line 70, in __iter__
    yield next(self._infinite_iterator)
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1068, in _next_data
    idx, data = self._get_data()
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1034, in _get_data
    success, data = self._try_get_data()
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 872, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 282, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.8/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.8/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 508, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 757, in answer_challenge
    response = connection.recv_bytes(256)        # reject large message
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 899, in update
    self.network.parameters().grad = grads
AttributeError: 'generator' object has no attribute 'grad'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 899, in update
    torch.autograd.backward(grads)
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 899, in update
    p.grad = g
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/tensor.py", line 962, in grad
    self._grad = new_grad
RuntimeError: assigned grad has data of a different size
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 900, in update
    p.grad = g
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/tensor.py", line 962, in grad
    self._grad = new_grad
RuntimeError: assigned grad has data of a different size
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 900, in update
    p.grad = g
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/tensor.py", line 962, in grad
    self._grad = new_grad
RuntimeError: assigned grad has data of a different size
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 900, in update
    p.grad = g
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/tensor.py", line 962, in grad
    self._grad = new_grad
RuntimeError: assigned grad has data of a different size
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 900, in update
    p.grad = g
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/tensor.py", line 962, in grad
    self._grad = new_grad
RuntimeError: assigned grad has data of a different size
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 898, in update
    for i, (p, g) in enumerate(grads, self.network.parameters()):
TypeError: 'generator' object cannot be interpreted as an integer

Process Process-129:
Process Process-40:
Process Process-115:
Traceback (most recent call last):
Process Process-117:
  File "/usr/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
Process Process-126:
Process Process-118:
Traceback (most recent call last):
Process Process-119:
Process Process-132:
Traceback (most recent call last):
Process Process-136:
Process Process-135:
Traceback (most recent call last):
Process Process-11:
Traceback (most recent call last):
Process Process-125:
Traceback (most recent call last):
Process Process-4:
Traceback (most recent call last):
Process Process-12:
Traceback (most recent call last):
Process Process-13:
Process Process-124:
Traceback (most recent call last):
Process Process-127:
  File "/usr/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
Process Process-133:
Process Process-134:
  File "/usr/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 350, in _exit_function
    for p in active_children():
Process Process-128:
  File "/usr/lib/python3.8/multiprocessing/process.py", line 47, in active_children
    _cleanup()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 63, in _cleanup
    for p in list(_children):
KeyboardInterrupt
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
Process Process-29:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 195, in _finalize_join
    thread.join()
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
  File "/usr/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 195, in _finalize_join
    thread.join()
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 195, in _finalize_join
    thread.join()
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 195, in _finalize_join
    thread.join()
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
  File "/usr/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 350, in _exit_function
    for p in active_children():
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 48, in active_children
    return list(_children)
KeyboardInterrupt
  File "/usr/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 334, in _exit_function
    _run_finalizers(0)
  File "/usr/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 213, in __call__
    try:
KeyboardInterrupt
  File "/usr/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 195, in _finalize_join
    thread.join()
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
  File "/usr/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 195, in _finalize_join
    thread.join()
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
  File "/usr/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 195, in _finalize_join
    thread.join()
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 334, in _exit_function
    _run_finalizers(0)
  File "/usr/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 205, in _finalize_close
    notempty.notify()
  File "/usr/lib/python3.8/threading.py", line 354, in notify
    waiters_to_notify = _deque(_islice(all_waiters, n))
KeyboardInterrupt
  File "/usr/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 195, in _finalize_join
    thread.join()
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
  File "/usr/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 195, in _finalize_join
    thread.join()
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
  File "/usr/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 195, in _finalize_join
    thread.join()
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 195, in _finalize_join
    thread.join()
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
  File "/usr/lib/python3.8/multiprocessing/util.py", line 360, in _exit_function
    _run_finalizers()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 195, in _finalize_join
    thread.join()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 195, in _finalize_join
    thread.join()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 195, in _finalize_join
    thread.join()
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
  File "/usr/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 195, in _finalize_join
    thread.join()
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/util.py", line 353, in _exit_function
    p._popen.terminate()
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 61, in terminate
    self._send_signal(signal.SIGTERM)
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 49192) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 230, in <module>
    acc = misc.accuracy(algorithm, loader, weights, device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/lib/misc.py", line 124, in accuracy
    batch_weights = batch_weights.to(device)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 897, in update
    grads = self.mask_grads(self.tau, gradients)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 918, in mask_grads
    print(ge_all.shape)
AttributeError: 'tuple' object has no attribute 'shape'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 901, in update
    p.grad = g
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/tensor.py", line 962, in grad
    self._grad = new_grad
RuntimeError: assigned grad has data of a different size
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 901, in update
    p.grad = g
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/tensor.py", line 962, in grad
    self._grad = new_grad
RuntimeError: assigned grad has data of a different size
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 901, in update
    p.grad = g
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/tensor.py", line 962, in grad
    self._grad = new_grad
RuntimeError: assigned grad has data of a different size
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 901, in update
    p.grad = g
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/tensor.py", line 962, in grad
    self._grad = new_grad
RuntimeError: assigned grad has data of a different size
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 903, in update
    grads = self.mask_grads(self.tau, gradients)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 915, in mask_grads
    print(len(gradients[0]))
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 902, in update
    grads = self.mask_grads(self.tau, gradients)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 961, in mask_grads
    return g_masked
UnboundLocalError: local variable 'g_masked' referenced before assignment
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 906, in update
    return {'loss': total_loss.item()}
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 906, in update
    return {'loss': total_loss.item()}
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 896, in update
    env_grads = autograd.grad(env_loss, self.params, retain_graph=True)
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 202, in grad
    return Variable._execution_engine.run_backward(
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 902, in update
    
UnboundLocalError: local variable 'grads' referenced before assignment
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 906, in update
    return {'loss': total_loss.item()}
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 905, in update
    return {'loss': total_loss.item()}
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 230, in <module>
    acc = misc.accuracy(algorithm, loader, weights, device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/lib/misc.py", line 118, in accuracy
    p = network.predict(x)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 97, in predict
    return self.network(x)
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/networks.py", line 136, in forward
    x = self.conv4(x)
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 230, in <module>
    acc = misc.accuracy(algorithm, loader, weights, device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/lib/misc.py", line 124, in accuracy
    batch_weights = batch_weights.to(device)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 230, in <module>
    acc = misc.accuracy(algorithm, loader, weights, device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/lib/misc.py", line 124, in accuracy
    batch_weights = batch_weights.to(device)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 904, in update
    grads = self.mask_grads(self.tau, param_gradients)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 947, in mask_grads
    ge_cat = torch.cat(ge_all)
RuntimeError: Tensors must have same number of dimensions: got 1 and 4
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 903, in update
    grads = self.mask_grads(self.tau, param_gradients)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 946, in mask_grads
    ge_cat = torch.cat(ge_all)
RuntimeError: Tensors must have same number of dimensions: got 1 and 4
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 903, in update
    grads = self.mask_grads(self.tau, param_gradients)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 943, in mask_grads
    ge_cat = torch.cat(ge_all)
RuntimeError: Tensors must have same number of dimensions: got 1 and 4
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 902, in update
    grads = self.mask_grads(self.tau, param_gradients)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 942, in mask_grads
    ge_cat = torch.cat(ge_all)
RuntimeError: Tensors must have same number of dimensions: got 1 and 4
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 882, in update
    param_gradients = [[] for _ in self.params]
  File "/home/jcaudet/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'ILC' object has no attribute 'params'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 900, in update
    grads = self.mask_grads(self.tau, param_gradients, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 909, in mask_grads
    assert len(grads) == n_agreement_envs
NameError: name 'n_agreement_envs' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 900, in update
    grads = self.mask_grads(self.tau, param_gradients, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 911, in mask_grads
    assert grads.shape == (n_agreement_envs,) + param.shape
NameError: name 'n_agreement_envs' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 900, in update
    grads = self.mask_grads(self.tau, param_gradients, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 912, in mask_grads
    mask = torch.mean(grad_signs, dim=0).abs() >= agreement_threshold
NameError: name 'agreement_threshold' is not defined
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 900, in update
    grads = self.mask_grads(self.tau, param_gradients, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 939, in mask_grads
    ge_cat = torch.cat(ge_all)
RuntimeError: Tensors must have same number of dimensions: got 1 and 4
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 900, in update
    grads = self.mask_grads(self.tau, param_gradients, self.network.parameters())
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 939, in mask_grads
    ge_cat = torch.cat(ge_all)
RuntimeError: Tensors must have same number of dimensions: got 1 and 4
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/scripts/train.py", line 213, in <module>
    step_vals = algorithm.update(minibatches_device, uda_device)
  File "/home/jcaudet/Documents/GitRepos/DomainBed/domainbed/algorithms.py", line 904, in update
    return {'loss': mean_loss.item()}
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
